// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_content_delivery_bucket": "ccc-hosting-dev",
    "aws_content_delivery_bucket_region": "ca-central-1",
    "aws_content_delivery_url": "http://ccc-hosting-dev.s3-website.ca-central-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "ca-central-1:6fb8bb00-cf73-465e-976a-ef743c6705f1",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_l7SeSzgXn",
    "aws_user_pools_web_client_id": "1fhfp2hschs06pmfoa0k91i3es",
    "oauth": {
        "domain": "ccc-dev.auth.ca-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
